language: go
go:
  - 1.10.x
os:
  - osx
osx_image: xcode10.1
before_install:
  - brew update
  - brew install swig
  # already installed in travis-ci:
  # - brew install automake
  # - brew install cmake
  # - brew install libtool
  - rvm install 2.5.1
  - rvm use 2.5.1
install:
  - go get github.com/stretchr/testify
script:
  - ./build.sh test
  - ./go/build.sh test
  - ./python/build.sh test
  - ./ruby/build.sh test
